# Generated by Django 5.0.2 on 2024-08-17 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="productattr",
            name="attr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_attr",
                to="products.attr",
                verbose_name="Атрибут",
            ),
        ),
        migrations.AddField(
            model_name="productattr",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_product",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="attrs",
            field=models.ManyToManyField(
                through="products.ProductAttr",
                to="products.attr",
                verbose_name="Атрибуты продукта",
            ),
        ),
    ]
