# Generated by Django 5.0.2 on 2024-08-17 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="attrs",
            field=models.ManyToManyField(
                related_name="products",
                through="products.ProductAttr",
                to="products.attr",
                verbose_name="Атрибуты продукта",
            ),
        ),
        migrations.AlterField(
            model_name="productattr",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attrs",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
    ]
