# Generated by Django 5.0.2 on 2024-08-18 11:54

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_uniqueproduct"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uniqueproduct",
            options={
                "ordering": ("created",),
                "verbose_name": "Уникальный продукт",
                "verbose_name_plural": "Уникальные продукты",
            },
        ),
        migrations.AddField(
            model_name="uniqueproduct",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="uniqueproduct",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="uniqueproduct",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="id",
            ),
        ),
    ]
