# Generated by Django 5.0.2 on 2024-08-18 11:56

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_uniqueproduct_options_uniqueproduct_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uniqueproduct",
            name="attr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unique_products",
                to="products.productattr",
                verbose_name="Уникальный атрибут",
            ),
        ),
        migrations.AlterField(
            model_name="uniqueproduct",
            name="product",
            field=products.models.CustForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="unique_products",
                to="products.product",
                verbose_name="Уникальный продукт",
            ),
        ),
    ]
